name: lecle_crypto
description: Encrypt - Decrypt data
version: 0.0.1
author: kthangtd
homepage: 

publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  encrypt: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

